import { useEffect, useState } from "react";
const testimonials = [
  ["After three failed physiotherapy courses, Palazhi Ayurveda completely healed my frozen shoulder in eight weeks.", "Suresh Nair", "Orthopedic Services"],
  ["My mother walks independently again after geriatric rehabilitation and regular home visits.", "Priya Menon", "Geriatric Rehabilitation"],
  ["The respiratory programme reduced my asthma episodes and helped me breathe freely.", "Arun Kumar", "Respiratory Rehabilitation"],
  ["Five years of back pain gone after Panchakarma and Kati Vasti. Truly personalised treatment.", "Latha Krishnan", "Orthopedic Services"],
];
export default function Testimonials(){const[i,setI]=useState(0);useEffect(()=>{const id=setInterval(()=>setI(v=>(v+1)%testimonials.length),4500);return()=>clearInterval(id)},[]);const t=testimonials[i];return <><style>{`
.test-story{background:#f5efd9;padding:100px 5vw;font-family:Inter,system-ui,sans-serif;color:#26321f;position:relative}.test-card{max-width:880px;margin:auto;background:white;border:1px solid #edf0df;border-radius:38px;padding:54px;text-align:center;box-shadow:0 35px 100px rgba(92,72,38,.11);position:relative;overflow:hidden}.test-card:before{content:'“';position:absolute;top:-30px;left:35px;font-size:200px;font-family:Georgia,serif;color:#eef3df;line-height:1}.test-label{color:#789d43;font-weight:900;text-transform:uppercase;letter-spacing:.18em;font-size:12px}.test-card h2{font-family:Georgia,serif;font-size:clamp(34px,5vw,56px);margin:12px 0 28px}.test-card em{color:#779d42;font-weight:400}.quote{font-family:Georgia,serif;font-size:clamp(22px,3vw,34px);line-height:1.45;color:#3c4732;position:relative;z-index:1}.name{margin-top:28px;font-weight:900;color:#26321f}.role{color:#7a806e;margin-top:6px;font-weight:700}.dots{display:flex;gap:10px;justify-content:center;margin-top:30px}.dots button{width:10px;height:10px;border-radius:50%;border:0;background:#d9dfc5}.dots button.active{background:#638a32;transform:scale(1.3)}
`}</style><section className="test-story" id="testimonials"><div className="test-card"><span className="test-label">Patient Stories</span><h2>Voices of <em>healing</em></h2><div className="quote">“{t[0]}”</div><div className="name">{t[1]}</div><div className="role">{t[2]}</div><div className="dots">{testimonials.map((_,x)=><button className={x===i?'active':''} onClick={()=>setI(x)} key={x}/>)}</div></div></section></>}
